### ISSUE TITLE
Provide an example of propper use for reference

### ISSUE THREAD

**Issue by 4censord** [nickboucher/trojan-source#7]
It would be interesting to see how a simple, non malicious comment is seen by today's warnings. 

I would recomend a having at least
* a copyright notice 
* and a function comment ala `// ask Joe why this works`
* A multi paragraph comment explaining a concept.

**Comment by nickboucher** [comment]
Hi @4censord --

First, thanks for the copyright notice point; I've realized that this repo was missing a license, and I've added an MIT License just now.

For the other points, I completely agree that these examples would be useful and interesting. My goal for this repo is to keep the examples very simple and closely related to what would be found in the [related paper](https://trojansource.codes/trojan-source.pdf). My recommendation would be to make a new repo that contains these examples, and to circle back to this issue with a link so that it can be easily found. If you choose to do this, I'll be interested to see what kind of examples you come up with!
